package com.qinhailin.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		if(arp.getConfig().getName()=="main") {
		arp.addMapping("file_uploaded", "id", FileUploaded.class);
		arp.addMapping("sys_function", "id", SysFunction.class);
		arp.addMapping("sys_org", "id", SysOrg.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_role_function", "id", SysRoleFunction.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("sys_user_role", "id", SysUserRole.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("data_dictionary", "id", DataDictionary.class);
		arp.addMapping("data_dictionary_value", "id", DataDictionaryValue.class);
		}else {
			//arp.addMapping("V_ID_CARD_MESSAGE", "id", OAMessage.class);
			arp.addMapping("T_OA_MESSAGE_IF_DATA", "RKEY", OAMessage.class);
			arp.addMapping("T_OA_MESSAGE", "RKEY", OAMessageTimmer.class);
		}
		//arp.addMapping("V_ID_CARD_MESSAGE", "id", OAMessage.class);
	}
}

